fix(todo): Fix method name - use getSessionById instead of get
SessionRepository doesn't have a get() method - it has getSessionById().
Todo tool was calling the wrong method name.

Error: sessionRepository.get is not a function
Fix: Changed to sessionRepository.getSessionById(sessionId)